#!/usr/bin/env bash
#  Bash script that gives you information about the rca school file.

if [ -e "rca chool" ]
then
  echo "school file exists"
  if [ -s "rca chool" ]
  then
    echo "school file is not empty"
  else
    echo "school file is empty"
  fi

  if [ -f "rca chool" ]
  then
    echo "school file is a regular file"
  fi
else
  echo "school file does not exist"
fi
